### ISSUE TITLE
SignatureDoesNotMatch error while uploading the file. PreSigned URL doesn't work when trying to upload file.

### ISSUE THREAD

**Issue by collegeimprovements** [aws-beam/aws_signature#10]
With the generated `signed_url` we are able to download or get the file.
However when we try to upload the file via curl or postman, we keep getting `SignatureDoesNotMatch` error.

We have the following code to generate `signed_url`.  
```elixir
  def get_signed_url(full_object_path, opts \\ [ttl: 86_400]) do
    access_key = System.get_env("S3_ACCESS_KEY", "default_access_key")
    secret_key = System.get_env("S3_SECRET_KEY", "default_secret_key")
    region = System.get_env("S3_REGION", "us-east-1")
    datetime = :erlang.universaltime()

    base_url =
      System.get_env("S3_BASE_URL", "https://#{bucket_name}.us-east-1.linodeobjects.com")

    url = "#{base_url}/#{full_object_path}"

    signed_url =
      :aws_signature.sign_v4_query_params(
        access_key,
        secret_key,
        region,
        "S3",
        datetime,
        url,
        opts
      )

    signed_url
  end
```

And we keep getting the following error while trying to upload the file via curl or postman.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <RequestId>tx000000000000019e1ca22-00614d6d01-27378aa-default</RequestId>
    <HostId>27378aa-default-default</HostId>
</Error>
```

Here is one of such generated url which is valid for 30 days: [Link](https://vydl-s3-ca-central.us-east-1.linodeobjects.com/abcd/try.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=8VCE820D8KR3CX53LTY7%2F20210924%2Fus-east-1%2FS3%2Faws4_request&X-Amz-Date=20210924T065347Z&X-Amz-Expires=2592000&X-Amz-Signature=3acebac71a0b678ecdd2c8111ad7428d79c93a5122465381bff248fae6e41a29&X-Amz-SignedHeaders=host)

Ref: https://github.com/aws-beam/aws-elixir/issues/90

**Comment by jonatanklosko** [comment]
My first guess is that it's the fact that we hardcode GET as the method when signing query params:

https://github.com/aws-beam/aws_signature/blob/a0ed23b6c02d48a6d9fa6b2c68ecd1fa25058bc4/src/aws_signature.erl#L174

I attempted a quick fix in https://github.com/aws-beam/aws_signature/commit/c737cca3241a05e3dfa312ec258d283aaaa94a31, you can try it out by installing from `github: "aws-beam/aws_signature", branch: "jk-query-method"`.

**Comment by collegeimprovements** [comment]
Thanks a lot @jonatanklosko. Let me test it. Generally one can upload file via both put or post method. But if we can do it via any one of them it would be good enough.

**Comment by collegeimprovements** [comment]
Now I get `access denied` error with the same keys. 
With the same keys I can upload file via `aws` package.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <RequestId>tx00000000000001a179814-00614e073f-273cb90-default</RequestId>
    <HostId>273cb90-default-default</HostId>
</Error>
```

**Comment by jonatanklosko** [comment]
Did you use PUT or POST?

**Comment by collegeimprovements** [comment]
I tried with PUT

**Comment by jonatanklosko** [comment]
Hmm, so that's in line with [the docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html):

> an HTTP method (PUT for uploading objects)

**Comment by jonatanklosko** [comment]
Though if you get AccessDenied I think it means the signature is correct, any change to the signature would cause mismatch again :thinking:

**Comment by collegeimprovements** [comment]
Yes, interestingly the same tokens work and I can upload(put) files on storage with aws-s3.

**Comment by collegeimprovements** [comment]
If you want, I can even share the keys if that helps.

**Comment by jonatanklosko** [comment]
Thanks, I have some around for my bucket. I will later try generating the presigned URL in another language to see if it matches.

**Comment by jonatanklosko** [comment]
So I actually managed to upload a file using the adjusted version.

Generated the URL with:

```elixir
Mix.install([
  {:aws_signature, "~> 0.1.1", github: "aws-beam/aws_signature", branch: "jk-query-method"}
])

access_key_id = "ACCESS KEY"
secret_access_key = "SECRET ACCESS KEY"
region = "eu-central-1"
service = "s3"
date_time = :calendar.universal_time()
method = "PUT"
url = "https://s3.eu-central-1.amazonaws.com/jonatanklosko-livebook-test/uploaded.txt"

:aws_signature.sign_v4_query_params(access_key_id, secret_access_key, region, service, date_time, method, url, [])
```

And then uploaded a file using `curl`:

```shell
curl -v --upload-file LICENSE 'generated url'
```

So I think the signature is correct, access issue must lie elsewhere :thinking:

**Comment by collegeimprovements** [comment]
Thanks a lot @jonatanklosko for ⚡️ reply.

If it's working for AWS-S3, it should work for Linode Storage as it's fully S3-compliant. 
I checked again with your code and got the same `403- AccessDenied ` error. 
I even tried to give bucket full public read+write permission but go the same error back.
Interestingly via `aws-beam/aws` package I'm able to upload/put the files. 

I'll try to dig find out the why from Linode's side. I'll keep you posted here.

**Comment by jonatanklosko** [comment]
So the original error is fixed by #11, I'm going to close this one and release 0.2.0. If you figure out the access denied error is somehow related to the signature let us know!

**Comment by collegeimprovements** [comment]
Sure. Thanks a lot @jonatanklosko

**Comment by collegeimprovements** [comment]
UPDATE: Was able to upload file successfully with Minio. And also on Linode Storage with a small hack. I've raised the issue with Linode. But all looks good. Thanks again @jonatanklosko  😃

**Comment by jonatanklosko** [comment]
@collegeimprovements awesome, thanks for the update! :)
