### ISSUE TITLE
Cannot get presigned urls to work - Signatures does not match

### ISSUE THREAD

**Issue by volkerholloh** [aws-beam/aws_signature#20]
Hi Jonatan, hi there,

firstly I want to send my warm regards for you making this library and maintaining it. :)

I want to use this library to download files into my app with a presigned url and build upon what user Collegeimprove did in the other issues:

```
defmodule MyAppWeb.S3Helper do

# export S3_BASE_URL=https://MY_BUCKET.s3-eu-central-1.amazonaws.com
# export S3_REGION=eu-central-1

def get_signed_url(
        full_object_path,
        opts \\ [ttl: 86_400]
      ) do
    access_key = System.get_env("S3_ACCESS_KEY_ID")
    secret_key = System.get_env("S3_SECRET_ACCESS_KEY")
    region = System.get_env("S3_REGION")
    datetime = :erlang.universaltime()
    method = "GET"

    base_url = System.get_env("S3_BASE_URL")

    url = "#{base_url}/#{full_object_path}"

    signed_url =
      :aws_signature.sign_v4_query_params(
        access_key,
        secret_key,
        region,
        "s3",
        datetime,
        method,
        url,
        opts
      )

    signed_url
  end

end
```

I am calling this function like this: 
`iex(1)> MyAppWeb.S3Helper.get_signed_url("myfile.PDF", ttl: 3600, body_digest: "UNSIGNED-PAYLOAD")`

getting as a result:
```
"https://MY_S3_BUCKET.s3-eu-central-1.amazonaws.com/myfile.PDF?
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Credential=AKMYCREDENTIAL%2F20221012%2Feu-central-1%2Fs3%2Faws4_request&
X-Amz-Date=20221012T060833Z&
X-Amz-Expires=3600&
X-Amz-Signature=20e388fb83b11a0bd7a9304f5efec61f710a14dcd31038e2bc30423898097e4c&
X-Amz-SignedHeaders=host"
```

But I am getting this error, when I click on the link, which I expect to work and provide the file:
```
`<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>`
```

My app is using the same credentials etc. like the function above and the files have been uploaded via the method posted here https://hexdocs.pm/phoenix_live_view/uploads-external.html by Chris McCord.

I am at wit's end and obviously a beginner, but do you have an idea what I am doing wrong?

Kind regards,
Volker

**Comment by jonatanklosko** [comment]
Hey Volker! Everything looks good to me, the only relevant difference I can see from what we've seen so far is that the URL includes the region. Does it work if you change `s3-eu-central-1.amazonaws.com` to `s3.amazonaws.com`?

**Comment by volkerholloh** [comment]
Thank you, Jonatan, for your help!

The URL was correct, though. The culprit was, that spaces within the filename are escaped differently as it seems. When I went into the S3 console, Amazon escapes spaces as "+" characters, when you copy the url. Within my code they are escaped to %20, which lead to different results after signing, of course.

With a filename like "test.pdf" everything worked. :) Now I know what to do. :)

Thanks again!

Kind regards,
Volker

**Comment by volkerholloh** [comment]
Yes, very confusing!

I mean by copying the file url like this: 
![CleanShot 2022-10-12 at 13 43 21@2x](https://user-images.githubusercontent.com/2065286/195334272-469e0a69-4c40-4f7b-9731-e12b3d4f5d4f.png)

**Comment by jonatanklosko** [comment]
You mean this copies the URL with the signature and the path includes `+` rather than `%20`?

**Comment by volkerholloh** [comment]
Exactly. 
![CleanShot 2022-10-12 at 13 52 05@2x](https://user-images.githubusercontent.com/2065286/195335799-9d46cc42-e042-4e52-b754-847cc6303d43.png)

The file will become `LOHNabrechnung+(Formular+Plus).PDF`

**Comment by jonatanklosko** [comment]
Interesting, thanks for the details!

**Comment by jonatanklosko** [comment]
Ah, I've just checked and the `Copy URL` doesn't include the signature, so then `+` is fine. If you do `Actions > Share with a presigned URL` and generate the URL, it will actually have `%20` as expected.
